# Generated by Django 4.2.3 on 2023-07-25 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_user_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('signed_by', models.CharField(max_length=25)),
                ('certificate_id', models.CharField(max_length=250, unique=True)),
            ],
        ),
    ]
