# Generated by Django 4.2.3 on 2023-07-25 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_certificate'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='certificate',
            new_name='certificate_model',
        ),
    ]
