# Generated by Django 4.2.3 on 2023-07-27 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_certificate_model_certificate_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate_model',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='certificate_model',
            name='signed_by',
            field=models.CharField(max_length=100),
        ),
    ]
